name: test workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      prefix: stg
    steps:
      - name: Convert to uppercase
        run: |
          STG_KEY=iamStgKey
          _ENV=${{env.prefix}}
          key_name="${_ENV}^^_KEY"
          echo $key_name
          2key_name="${${{ env.prefix }}^^}_KEY"
          echo $2key_name
