name: test workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      prefix: stg
    steps:
      - name: Convert to uppercase
        run: |
          STG_KEY=iamStgKey
          key_name="${{ env.prefix }}^^_KEY"
          echo $key_name
